permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author: 
  name: 王励志
  email: rocking1216@163.com
  link: http://rockingwang.github.io
  weibo: http://weibo.com/u/1728424765
  github: https://github.com/RockingWang

# 站点信息
title: 王励志的博客 
description: 王励志的博客
url: http://rockingwang.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico